//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string Nivel { get; set; }
        public string Que { get; set; }
        public string Donde { get; set; }
        public System.DateTime Cuando { get; set; }
        public int Quien { get; set; }
        public string Resultado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
